# config/zed_params.yaml
# Stereolabs ZED Stereo camera parameters override file
# This file is used to override the default parameters of the ZED camera.

/**:
    ros__parameters:
        general:
          grab_resolution: 'HD1080' # The native camera grab resolution. 'HD1200', 'HD1080', 'SVGA', 'AUTO'
          grab_frame_rate: 30 # ZED SDK internal grabbing rate (HD1200/HD1080: 60, 30, 15 - SVGA: 120, 60, 30, 15)
          pub_resolution: 'NATIVE'
          pub_frame_rate: 30.0